# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestDemo01():
  def setup_method(self, method):
    chrome_arg = webdriver.ChromeOptions()
    chrome_arg.debugger_address ='127.0.0.1:9222'
    # 浏览器复用
    # self.driver = webdriver.Chrome(options=chrome_arg)
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()


  # def test_demo01(self):
  #   """
  #   浏览器复用
  #   :return:
  #   """
  #   self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
  #   self.driver.find_element(By.XPATH, "//*[@id='menu_contacts']").click()
  #   time.sleep(6)
  #   # 存入 cookie
  #   cookies = self.driver.get_cookies()
  #   with open("tmp01.text", "w", encoding="utf-8") as f:
  #     json.dump(cookies, f)
  #   self.driver.close()

  def test_cookie_login(self):
    """
    利用cookeie 进行登录
    :return:
    """
    # 读取 cookie
    self.driver.get("https://work.weixin.qq.com/wework_admin/frame#index")
    with open("tmp01.text", "r", encoding="utf-8") as f:
      # 序列化
      cookies = json.load(f)
    for i in cookies:
      self.driver.add_cookie(i)
    self.driver.refresh()
    time.sleep(6)
